# docker-compose.yml
version: '3.8'

services:

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: secondPrometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml

  web-app:
    build:
      context: ../../SRE-monitoring  # Path to the directory containing the Dockerfile
    container_name: web-app
    ports:
      - "3030:3030"
    #should be maybe added volumes section (currently no refresh)

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafanaDockerCompose
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus