# prometheus.yml
global:
  scrape_interval: 5s  # Set the default scrape interval

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 

scrape_configs:
  - job_name: 'secondPrometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrape itself (Prometheus metrics)
    
  - job_name: 'my_http_job'
    static_configs:
      - targets:
          - 'web-app:3030'  # Replace with actual HTTP endpoint
          - 'localhost:9090'
          - 'localhost:27017'  # Add more endpoints as needed