apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1 #can be more but for what really
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - containerPort: 9093
---
#service
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  selector:
    name: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093