apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1 #can be more but for what really
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana-oss:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: grafana-password
---
#service
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000